apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-deployment
    spec:
      containers:
        - name: hello-world
          image: helloworld-webserver:1.0
      nodeSelector:
        example.com/nodelabel1: "somevalue"